version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-data:/data/db

  app:
    container_name: products-api
    build: ./
    ports:
      - 8080:8080



